name: Find added or modified RFCs
description: 'Find added or modified RFC'

# Any workflow using this action requires using actions/checkout with a fetch-depth: 0

inputs:
  base-sha:
    description: 'Base SHA'
    required: false
  sha:
    description: 'SHA'
    required: false

outputs:
  modified-rfc:
    description: "The path of the RFC that was added or modified"
    value: ${{ steps.modified-rfc.outputs.path }}
  modified-rfcs-count:
    description: "The count of how many RFCs were added or modified"
    value: ${{ steps.rfcs.outputs.all_changed_files_count }}
  added-rfcs-count:
    description: "The count of how many RFCs that were added"
    value: ${{ steps.rfcs.outputs.added_files_count }}

runs:
  using: "composite"
  steps:
    - name: Find added or modified RFCs
      id: rfcs
      uses: tj-actions/changed-files@v39
      with:
        files: text
        json: true

    - name: Find modified or added RFC info
      id: modified-rfc
      shell: bash
      run: |
        changed_file=`echo "${{ steps.rfcs.outputs.all_changed_files }}" | jq '.[0]'`
        echo "path=$changed_file" >> $GITHUB_OUTPUT
