name: Setup RFCs Tooling
description: 'Setup RFCs Tooling'

inputs:
  token:
    description: 'GitHub token with repo permissions'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: emberjs/rfcs-tooling
        path: rfcs-tooling
        ref: 'v1.2.0'

    - uses: actions/setup-node@v3

    - run: yarn install
      shell: bash
      working-directory: rfcs-tooling
