name: Open PR to advance to the next stage of an advanced RFC

on:
  push:
    branches: [ main, master ]
    paths:
      - 'text/*.md'

jobs:
  advance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: emberjs/rfcs-tooling
        path: rfcs-tooling
        ref: 'v1.1.0'

    - name: Find added or modified RFCs
      id: rfcs
      uses: tj-actions/changed-files@v25
      with:
        path: 'text'
        json: 'true'

    - name: Fail if more than 1 RFC is added or modified
      run: |
        len=`echo "${{ steps.rfcs.outputs.all_changed_files }}" | jq '. | length'`
        echo "RFCs added or modified: ${{ steps.rfcs.outputs.all_changed_files }}"
        if [[ $len > 1 ]]; then
          echo "::error::More than 1 RFC is added or modified"
          exit 1
        fi

# fail if more than one RFC has been edited or added in RFC texts/
# On merged PR that is a newly added RFC or has CHANGED THE STAGE
# Update metadata + commit
# Open PR w/template and label
# git show HEAD~4:src/main.c  ${{ github.event.push.base.sha }}
