name: Open PR to advance an RFC to the next stage

on:
  push:
    branches: [ main, master ]
    paths:
      - 'text/*.md'

jobs:
  advance-rfc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: emberjs/rfcs-tooling
        path: rfcs-tooling
        ref: 'kg-create-prs'

    - uses: actions/setup-node@v2.1.2

    - run: yarn install
      working-directory: rfcs-tooling

    - name: Find added or modified RFCs
      id: rfcs
      uses: tj-actions/changed-files@v25
      with:
        path: 'text'
        json: 'true'

    - name: Fail if more than 1 RFC is added or modified
      run: |
        len=`echo "${{ steps.rfcs.outputs.all_changed_files }}" | jq '. | length'`
        echo "RFCs added or modified: ${{ steps.rfcs.outputs.all_changed_files }}"
        if [[ $len > 1 ]]; then
          echo "::error::More than 1 RFC is added or modified in this PR; unable to automatically open PRs for advancement"
          exit 1
        fi

    - name: Find modified or added RFC path
      id: modified_rfc
      run: |
        changed_file=`echo "${{ steps.rfcs.outputs.all_changed_files }}" | jq '.[0]'`
        echo "::set-output name=path::$changed_file" 
        pr_number="${changed_file//[!0-9]/}"
        echo "::set-output name=pr_number::$pr_number"

    - name: Determine if stage has changed
      id: has_stage_changed
      working-directory: rfcs-tooling
      run: |
        len=`echo "${{ steps.rfcs.outputs.added_files }}" | jq '. | length'`
        if [[ $len == 1 ]]; then
          echo "::set-output name=value::true"
        else
          if `node has-stage-changed.js ${{ github.event.push.base.sha }} ${{ steps.modified_rfc.outputs.path }}`; then
            echo "::set-output name=value::true"
          else
            echo "::set-output name=value::false"
          fi
        fi

    - name: Update frontmatter
      id: stage
      if: ${{ steps.has_stage_changed.outputs.value }} == true
      working-directory: rfcs-tooling
      run: |
        new_stage=`node find-next-stage.js ${{ steps.modified_rfc.outputs.path }}`
        echo "::set-output name=value::$new_stage"
        node update-rfc-stage.js $new_stage ${{ steps.modified_rfc.outputs.path }}
# TODO: Check for existing open PRs to avoid infinite PRs
    - name: Open PR
      if: ${{ steps.has_stage_changed.outputs.value }} == true
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: "Advance RFC to Stage ${{ steps.stage.outputs.value }}"
        branch: "advance-rfc-${{ steps.modified_rfc.outputs.pr_number }}"
        title: "Advance RFC #${{ steps.modified_rfc.outputs.pr_number}} to Stage ${{ steps.stage.outputs.value }}"
        # Make templates for body of PRs
        body: "Advance RFC #${{ steps.modified_rfc.outputs.pr_number}} to Stage ${{ steps.stage.outputs.value }}"
        labels: 'RFC Advancement' # Add labels for stage, requires-fcp
        # team-reviewers // set on advances to ready-for-release

# workflow to add PR link to metadata
