name: Ensure Labels of New RFCs

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened]
    paths:
      - 'text/*.md'

jobs:
  check-filename:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Changed Files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Filter Added Files to Added RFCs
        id: files
        run: |
          added_files=`jq -r '[.[] | select(startswith("text/"))] | join(" ")' ${HOME}/files_added.json`
          echo "::set-output name=added::$added_files"

      - name: Get Labels
        id: labels
        run: |
          labels=${{ github.event.pull_request.labels }}
          echo "::set-output name=labels::$labels"
          echo $labels

      - name: Ensure the RFC is in the Exploring Stage before merge is allowed
        if: steps.files.added.length > 0
        run: |
          echo "${{ steps.labels.outputs.labels }}"
