name: Ensure Stage of New RFCs before Merge

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened]
    paths:
      - 'text/*.md'

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Changed Files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Filter Added Files to Added RFCs
        id: files
        run: |
          added_files=`jq -r '[.[] | select(startswith("text/"))] | join(" ")' ${HOME}/files_added.json`
          echo "::set-output name=added::$added_files"

      - name: Ensure the RFC is in the Exploring Stage before merge is allowed
        if: steps.files.outputs.added && !contains(${{ github.event.pull_request.labels }}, 'S-Exploring')
        run: |
          echo "RFCs must advance to the Exploring Stage before merging to Accepted is allowed"
          exit 1

# Ensure only one RFC is added, or advancement won't work
