name: Ensure Stage of New RFCs before Merge

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened]
    paths:
      - 'text/*.md'

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Find added or modified RFCs
        id: rfcs
        uses: tj-actions/changed-files@v25
        with:
          path: 'text'
          json: 'true'

      - name: Ensure the RFC is in the Exploring Stage before merge is allowed
        if: steps.rfcs.outputs.added && !contains(${{ github.event.pull_request.labels }}, 'S-Exploring')
        run: |
          echo "RFCs must advance to the Exploring Stage before merging to Accepted is allowed"
          exit 1
