name: Label newly opened RFC PRs

on:
  pull_request_target: # This workflow has permissions on the repo, do NOT run code from PRs in this workflow. See https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    types: [opened]
    paths:
      - 'text/*.md'

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          persist-credentials: false

      - name: Find added or modified RFCs
        id: rfcs
        uses: tj-actions/changed-files@v25
        with:
          path: 'text'
          sha: ${{ github.event.pull_request.head.sha }}
          base_sha: ${{ github.event.pull_request.base.sha }}
          json: 'true'

      - run: |
          echo "${{ toJSON(steps.rfcs.outputs.added_files) }}"

      - uses: actions-ecosystem/action-add-labels@v1
        if: steps.rfcs.outputs.added_files
        with:
          labels: S-Proposed
