name: Setup RFCs Tooling

on:
  workflow_call:

jobs:
  checkout-tools-and-install:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: emberjs/rfcs-tooling
          path: rfcs-tooling
          ref: 'v1.2.0'

      - uses: actions/setup-node@v3

      - run: yarn install
        working-directory: rfcs-tooling
